# run for all PRs and merges

stages:
- stage: Build_Test
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-build.yml
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-test.yml
  - job: Deploy
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-build.yml
      - template: jobs/default-deploy.yml

