trigger:
- master
- develop
- net5

stages:
- stage: Build_Test
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-build.yml
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-test.yml

