# run for all PRs and merges

stages:
- stage: Build_Test
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-build.yml
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-test.yml
  - job: Publish
    condition: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]
    displayName: Publish
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-publish.yml

