comment:
  require_changes: yes
coverage:
  status:
    project:
      default:
        target: 90%    # the required coverage value
        threshold: 0.1%  # the leniency in hitting the target
    patch:
      default:
        target: 100%
        threshold: 10%
  