changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking change
    - title: New Features
      labels:
        - new component
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - build
          - docs
          - tests
          - dependency
          - refactor
