// NOTE: this file is autogenerated. Any changes will be overwritten!
namespace MudBlazor.Docs.Models
{
    public static partial class Snippets
    {

public const string CodeInline = @"```html
<code class=""docs-code"">
    @Code
    @ChildContent
</code>

@code
{
    [Parameter] public RenderFragment ChildContent { get; set; }

    [Parameter] public string Code { get; set; }
}
```";
public const string TableCode1 = @"```html
<MudTable Items=""@PeriodicTable.GetElements()"" Dense=""@dense"" Hover=""@hover"" Filter=""new Func<Element,bool>(FilterFunc)"" @bind-SelectedItem=""selected_item"">
    <ToolBarContent>
        <MudText Typo=""Typo.h6"" Class=""mud-flex-1-1-100"">Periodic Elements</MudText>
        <MudIcon Style=""margin-top: 20px; margin-right: 8px;"" Icon=""@Icons.Material.Search""></MudIcon>
        <MudTextField @bind-Value=""search_string"" Placeholder=""Search""></MudTextField>
        <MudAppBarSpacer></MudAppBarSpacer>
    </ToolBarContent>
    <HeaderContent>
        <MudTh>Nr</MudTh>
        <MudTh>Sign</MudTh>
        <MudTh>Name</MudTh>
        <MudTh>Position</MudTh>
        <MudTh>Molar mass</MudTh>
    </HeaderContent>
    <RowTemplate>
        <MudTd>@context.Number</MudTd>
        <MudTd>@context.Sign</MudTd>
        <MudTd>@context.Name</MudTd>
        <MudTd>@context.Position</MudTd>
        <MudTd>@context.Molar</MudTd>
    </RowTemplate>
    <PagerContent>
        <MudTablePager />
    </PagerContent>
</MudTable>
<MudSwitch @bind-Checked=""@hover"" Color=""Color.Primary"">Hover</MudSwitch>
<MudSwitch @bind-Checked=""@dense"" Color=""Color.Secondary"">Dense</MudSwitch>
<MudText Inline=""true"">Selected: @selected_item?.Name</MudText>

@code {
    bool dense = false;
    bool hover = true;
    bool fixed_header = false;
    string search_string = """";
    Element selected_item = null;
    HashSet<Element> selected_items = new HashSet<Element>();

    bool FilterFunc(Element element)
    {
        if (string.IsNullOrWhiteSpace(search_string))
            return true;
        if (element.Sign.Contains(search_string))
            return true;
        if (element.Name.Contains(search_string))
            return true;
        if ($""{element.Number} {element.Position} {element.Molar}"".Contains(search_string))
            return true;
        return false;
    }
}
```";
public const string TableCode2 = @"```html
<MudTable Items=""@PeriodicTable.GetElements()"" MultiSelection=""true"" @bind-SelectedItems=""selected_items"" Hover=""@hover"">
    <HeaderContent>
        <MudTh>Nr</MudTh>
        <MudTh>Sign</MudTh>
        <MudTh><MudTableSortLabel>Name</MudTableSortLabel></MudTh>
        <MudTh>Position</MudTh>
        <MudTh>Molar mass</MudTh>
    </HeaderContent>
    <RowTemplate>
        <MudTd>@context.Number</MudTd>
        <MudTd>@context.Sign</MudTd>
        <MudTd>@context.Name</MudTd>
        <MudTd>@context.Position</MudTd>
        <MudTd>@context.Molar</MudTd>
    </RowTemplate>
    <PagerContent>
        <MudTablePager PageSizeOptions=""new List<int>(){50, 100}"" />
    </PagerContent>
</MudTable>
<MudText Inline=""true"">Selected items: @(selected_items==null ? """" : string.Join("", "", selected_items.OrderBy(x=>x.Sign).Select(x=>x.Sign)))</MudText>

@code {
    bool hover = true;
    HashSet<Element> selected_items = new HashSet<Element>();
}
```";
public const string TableCode3 = @"```html
<MudTable Items=""@PeriodicTable.GetElements()"" FixedHeader=""true"" Height=""400px"">
    <HeaderContent>
        <MudTh>Nr</MudTh>
        <MudTh>Sign</MudTh>
        <MudTh>Name</MudTh>
        <MudTh>Position</MudTh>
        <MudTh>Molar mass</MudTh>
    </HeaderContent>
    <RowTemplate>
        <MudTd>@context.Number</MudTd>
        <MudTd>@context.Sign</MudTd>
        <MudTd>@context.Name</MudTd>
        <MudTd>@context.Position</MudTd>
        <MudTd>@context.Molar</MudTd>
    </RowTemplate>
    <PagerContent>
        <MudTablePager PageSizeOptions=""new List<int>(){50, 100}"" />
    </PagerContent>
</MudTable>
<MudSwitch @bind-Checked=""@fixed_header"">Fixed Header</MudSwitch>

@code {
    bool fixed_header = true;
}
```";
    }
}

