//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudBlazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MudBlazor.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Alert.
        /// </summary>
        public static string MudAlert_Close {
            get {
                return ResourceManager.GetString("MudAlert_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string MudBaseDatePicker_Calendar {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Header.
        /// </summary>
        public static string MudBaseDatePicker_CalendarHeader {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_CalendarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Picker.
        /// </summary>
        public static string MudBaseDatePicker_Close {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string MudBaseDatePicker_DateClick {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_DateClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Month.
        /// </summary>
        public static string MudBaseDatePicker_Month {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Container.
        /// </summary>
        public static string MudBaseDatePicker_MonthContainer {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_MonthContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next month {0}.
        /// </summary>
        public static string MudBaseDatePicker_NextMonth {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next year {0}.
        /// </summary>
        public static string MudBaseDatePicker_NextYear {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to previous month {0}.
        /// </summary>
        public static string MudBaseDatePicker_PrevMonth {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_PrevMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to previous year {0}.
        /// </summary>
        public static string MudBaseDatePicker_PrevYear {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_PrevYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string MudBaseDatePicker_Week {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Year.
        /// </summary>
        public static string MudBaseDatePicker_YearClick {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_YearClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Container.
        /// </summary>
        public static string MudBaseDatePicker_YearContainer {
            get {
                return ResourceManager.GetString("MudBaseDatePicker_YearContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Chip.
        /// </summary>
        public static string MudChip_Close {
            get {
                return ResourceManager.GetString("MudChip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Alpha Slider.
        /// </summary>
        public static string MudColorPicker_AlphaSlider {
            get {
                return ResourceManager.GetString("MudColorPicker_AlphaSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Picker.
        /// </summary>
        public static string MudColorPicker_Close {
            get {
                return ResourceManager.GetString("MudColorPicker_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color from Collection.
        /// </summary>
        public static string MudColorPicker_ColorCollection {
            get {
                return ResourceManager.GetString("MudColorPicker_ColorCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color Dot.
        /// </summary>
        public static string MudColorPicker_ColorDot {
            get {
                return ResourceManager.GetString("MudColorPicker_ColorDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color from Grid.
        /// </summary>
        public static string MudColorPicker_ColorGrid {
            get {
                return ResourceManager.GetString("MudColorPicker_ColorGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Color Overlay.
        /// </summary>
        public static string MudColorPicker_ColorOverlay {
            get {
                return ResourceManager.GetString("MudColorPicker_ColorOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Color Selector.
        /// </summary>
        public static string MudColorPicker_ColorSelector {
            get {
                return ResourceManager.GetString("MudColorPicker_ColorSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Controls.
        /// </summary>
        public static string MudColorPicker_Controls {
            get {
                return ResourceManager.GetString("MudColorPicker_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Grid View.
        /// </summary>
        public static string MudColorPicker_GridView {
            get {
                return ResourceManager.GetString("MudColorPicker_GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Hue Slider.
        /// </summary>
        public static string MudColorPicker_HueSlider {
            get {
                return ResourceManager.GetString("MudColorPicker_HueSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Mode.
        /// </summary>
        public static string MudColorPicker_ModeSwitch {
            get {
                return ResourceManager.GetString("MudColorPicker_ModeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Palette Color.
        /// </summary>
        public static string MudColorPicker_PaletteColor {
            get {
                return ResourceManager.GetString("MudColorPicker_PaletteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Palette View.
        /// </summary>
        public static string MudColorPicker_PaletteView {
            get {
                return ResourceManager.GetString("MudColorPicker_PaletteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Alpha Value.
        /// </summary>
        public static string MudColorPicker_SetAlpha {
            get {
                return ResourceManager.GetString("MudColorPicker_SetAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Blue Value.
        /// </summary>
        public static string MudColorPicker_SetBlue {
            get {
                return ResourceManager.GetString("MudColorPicker_SetBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Green Value.
        /// </summary>
        public static string MudColorPicker_SetGreen {
            get {
                return ResourceManager.GetString("MudColorPicker_SetGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Hex Value.
        /// </summary>
        public static string MudColorPicker_SetHex {
            get {
                return ResourceManager.GetString("MudColorPicker_SetHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Hue Value.
        /// </summary>
        public static string MudColorPicker_SetHue {
            get {
                return ResourceManager.GetString("MudColorPicker_SetHue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Lightness Value.
        /// </summary>
        public static string MudColorPicker_SetLightness {
            get {
                return ResourceManager.GetString("MudColorPicker_SetLightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Red Value.
        /// </summary>
        public static string MudColorPicker_SetRed {
            get {
                return ResourceManager.GetString("MudColorPicker_SetRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Saturation Value.
        /// </summary>
        public static string MudColorPicker_SetSaturation {
            get {
                return ResourceManager.GetString("MudColorPicker_SetSaturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Spectrum View.
        /// </summary>
        public static string MudColorPicker_SpectrumView {
            get {
                return ResourceManager.GetString("MudColorPicker_SpectrumView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Current Color.
        /// </summary>
        public static string MudColorPicker_ToggleCurrentColor {
            get {
                return ResourceManager.GetString("MudColorPicker_ToggleCurrentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Filter.
        /// </summary>
        public static string MudDataGrid_AddFilter {
            get {
                return ResourceManager.GetString("MudDataGrid.AddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string MudDataGrid_Apply {
            get {
                return ResourceManager.GetString("MudDataGrid.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MudDataGrid_Cancel {
            get {
                return ResourceManager.GetString("MudDataGrid.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string MudDataGrid_Clear {
            get {
                return ResourceManager.GetString("MudDataGrid.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All Groups.
        /// </summary>
        public static string MudDataGrid_CollapseAllGroups {
            get {
                return ResourceManager.GetString("MudDataGrid.CollapseAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string MudDataGrid_Column {
            get {
                return ResourceManager.GetString("MudDataGrid.Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string MudDataGrid_Columns {
            get {
                return ResourceManager.GetString("MudDataGrid.Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        public static string MudDataGrid_contains {
            get {
                return ResourceManager.GetString("MudDataGrid.contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        public static string MudDataGrid_ends_with {
            get {
                return ResourceManager.GetString("MudDataGrid.ends with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equals.
        /// </summary>
        public static string MudDataGrid_equals {
            get {
                return ResourceManager.GetString("MudDataGrid.equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All Groups.
        /// </summary>
        public static string MudDataGrid_ExpandAllGroups {
            get {
                return ResourceManager.GetString("MudDataGrid.ExpandAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string MudDataGrid_False {
            get {
                return ResourceManager.GetString("MudDataGrid.False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string MudDataGrid_Filter {
            get {
                return ResourceManager.GetString("MudDataGrid.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter value.
        /// </summary>
        public static string MudDataGrid_FilterValue {
            get {
                return ResourceManager.GetString("MudDataGrid.FilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string MudDataGrid_Group {
            get {
                return ResourceManager.GetString("MudDataGrid.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string MudDataGrid_Hide {
            get {
                return ResourceManager.GetString("MudDataGrid.Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide All.
        /// </summary>
        public static string MudDataGrid_HideAll {
            get {
                return ResourceManager.GetString("MudDataGrid.HideAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string MudDataGrid_is {
            get {
                return ResourceManager.GetString("MudDataGrid.is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is after.
        /// </summary>
        public static string MudDataGrid_is_after {
            get {
                return ResourceManager.GetString("MudDataGrid.is after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is before.
        /// </summary>
        public static string MudDataGrid_is_before {
            get {
                return ResourceManager.GetString("MudDataGrid.is before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is empty.
        /// </summary>
        public static string MudDataGrid_is_empty {
            get {
                return ResourceManager.GetString("MudDataGrid.is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not.
        /// </summary>
        public static string MudDataGrid_is_not {
            get {
                return ResourceManager.GetString("MudDataGrid.is not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not empty.
        /// </summary>
        public static string MudDataGrid_is_not_empty {
            get {
                return ResourceManager.GetString("MudDataGrid.is not empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is on or after.
        /// </summary>
        public static string MudDataGrid_is_on_or_after {
            get {
                return ResourceManager.GetString("MudDataGrid.is on or after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is on or before.
        /// </summary>
        public static string MudDataGrid_is_on_or_before {
            get {
                return ResourceManager.GetString("MudDataGrid.is on or before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MudDataGrid_MoveDown {
            get {
                return ResourceManager.GetString("MudDataGrid.MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MudDataGrid_MoveUp {
            get {
                return ResourceManager.GetString("MudDataGrid.MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not contains.
        /// </summary>
        public static string MudDataGrid_not_contains {
            get {
                return ResourceManager.GetString("MudDataGrid.not contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not equals.
        /// </summary>
        public static string MudDataGrid_not_equals {
            get {
                return ResourceManager.GetString("MudDataGrid.not equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string MudDataGrid_Operator {
            get {
                return ResourceManager.GetString("MudDataGrid.Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Data.
        /// </summary>
        public static string MudDataGrid_RefreshData {
            get {
                return ResourceManager.GetString("MudDataGrid.RefreshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MudDataGrid_Save {
            get {
                return ResourceManager.GetString("MudDataGrid.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string MudDataGrid_ShowAll {
            get {
                return ResourceManager.GetString("MudDataGrid.ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string MudDataGrid_Sort {
            get {
                return ResourceManager.GetString("MudDataGrid.Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts with.
        /// </summary>
        public static string MudDataGrid_starts_with {
            get {
                return ResourceManager.GetString("MudDataGrid.starts with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string MudDataGrid_True {
            get {
                return ResourceManager.GetString("MudDataGrid.True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        public static string MudDataGrid_Ungroup {
            get {
                return ResourceManager.GetString("MudDataGrid.Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsort.
        /// </summary>
        public static string MudDataGrid_Unsort {
            get {
                return ResourceManager.GetString("MudDataGrid.Unsort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string MudDataGrid_Value {
            get {
                return ResourceManager.GetString("MudDataGrid.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle {0}.
        /// </summary>
        public static string MudNavGroup_ToggleExpand {
            get {
                return ResourceManager.GetString("MudNavGroup_ToggleExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page {0}.
        /// </summary>
        public static string MudPagination_CurrentPage {
            get {
                return ResourceManager.GetString("MudPagination_CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First page.
        /// </summary>
        public static string MudPagination_FirstPage {
            get {
                return ResourceManager.GetString("MudPagination_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last page.
        /// </summary>
        public static string MudPagination_LastPage {
            get {
                return ResourceManager.GetString("MudPagination_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string MudPagination_NextPage {
            get {
                return ResourceManager.GetString("MudPagination_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}.
        /// </summary>
        public static string MudPagination_PageIndex {
            get {
                return ResourceManager.GetString("MudPagination_PageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string MudPagination_PreviousPage {
            get {
                return ResourceManager.GetString("MudPagination_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Rating.
        /// </summary>
        public static string MudRatingItem_Label {
            get {
                return ResourceManager.GetString("MudRatingItem_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select AM.
        /// </summary>
        public static string MudTimePicker_AmClick {
            get {
                return ResourceManager.GetString("MudTimePicker_AmClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Number.
        /// </summary>
        public static string MudTimePicker_ClockNumber {
            get {
                return ResourceManager.GetString("MudTimePicker_ClockNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Stick.
        /// </summary>
        public static string MudTimePicker_ClockStick {
            get {
                return ResourceManager.GetString("MudTimePicker_ClockStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Picker.
        /// </summary>
        public static string MudTimePicker_Close {
            get {
                return ResourceManager.GetString("MudTimePicker_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Hour.
        /// </summary>
        public static string MudTimePicker_HourClick {
            get {
                return ResourceManager.GetString("MudTimePicker_HourClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour Dial.
        /// </summary>
        public static string MudTimePicker_HourDial {
            get {
                return ResourceManager.GetString("MudTimePicker_HourDial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Hour {0}.
        /// </summary>
        public static string MudTimePicker_HourRotation {
            get {
                return ResourceManager.GetString("MudTimePicker_HourRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Minute.
        /// </summary>
        public static string MudTimePicker_MinuteClick {
            get {
                return ResourceManager.GetString("MudTimePicker_MinuteClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute Dial.
        /// </summary>
        public static string MudTimePicker_MinuteDial {
            get {
                return ResourceManager.GetString("MudTimePicker_MinuteDial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Minute {0}.
        /// </summary>
        public static string MudTimePicker_MinuteRotation {
            get {
                return ResourceManager.GetString("MudTimePicker_MinuteRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker Content.
        /// </summary>
        public static string MudTimePicker_PickerContent {
            get {
                return ResourceManager.GetString("MudTimePicker_PickerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PM.
        /// </summary>
        public static string MudTimePicker_PmClick {
            get {
                return ResourceManager.GetString("MudTimePicker_PmClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Separator.
        /// </summary>
        public static string MudTimePicker_TimeSeparator {
            get {
                return ResourceManager.GetString("MudTimePicker_TimeSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle AM/PM.
        /// </summary>
        public static string MudTimePicker_ToggleAmPm {
            get {
                return ResourceManager.GetString("MudTimePicker_ToggleAmPm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        public static string MudTimePicker_Toolbar {
            get {
                return ResourceManager.GetString("MudTimePicker_Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar AM/PM.
        /// </summary>
        public static string MudTimePicker_ToolbarAmPm {
            get {
                return ResourceManager.GetString("MudTimePicker_ToolbarAmPm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar Hour Minute.
        /// </summary>
        public static string MudTimePicker_ToolbarHourMinute {
            get {
                return ResourceManager.GetString("MudTimePicker_ToolbarHourMinute", resourceCulture);
            }
        }
    }
}
