//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudBlazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MudBlazor.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Filter.
        /// </summary>
        public static string MudDataGrid_AddFilter {
            get {
                return ResourceManager.GetString("MudDataGrid.AddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string MudDataGrid_Apply {
            get {
                return ResourceManager.GetString("MudDataGrid.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MudDataGrid_Cancel {
            get {
                return ResourceManager.GetString("MudDataGrid.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string MudDataGrid_Clear {
            get {
                return ResourceManager.GetString("MudDataGrid.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All Groups.
        /// </summary>
        public static string MudDataGrid_CollapseAllGroups {
            get {
                return ResourceManager.GetString("MudDataGrid.CollapseAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string MudDataGrid_Column {
            get {
                return ResourceManager.GetString("MudDataGrid.Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string MudDataGrid_Columns {
            get {
                return ResourceManager.GetString("MudDataGrid.Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        public static string MudDataGrid_contains {
            get {
                return ResourceManager.GetString("MudDataGrid.contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        public static string MudDataGrid_ends_with {
            get {
                return ResourceManager.GetString("MudDataGrid.ends with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equals.
        /// </summary>
        public static string MudDataGrid_equals {
            get {
                return ResourceManager.GetString("MudDataGrid.equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All Groups.
        /// </summary>
        public static string MudDataGrid_ExpandAllGroups {
            get {
                return ResourceManager.GetString("MudDataGrid.ExpandAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string MudDataGrid_False {
            get {
                return ResourceManager.GetString("MudDataGrid.False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string MudDataGrid_Filter {
            get {
                return ResourceManager.GetString("MudDataGrid.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter value.
        /// </summary>
        public static string MudDataGrid_FilterValue {
            get {
                return ResourceManager.GetString("MudDataGrid.FilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string MudDataGrid_Group {
            get {
                return ResourceManager.GetString("MudDataGrid.Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string MudDataGrid_Hide {
            get {
                return ResourceManager.GetString("MudDataGrid.Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide All.
        /// </summary>
        public static string MudDataGrid_HideAll {
            get {
                return ResourceManager.GetString("MudDataGrid.HideAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string MudDataGrid_is {
            get {
                return ResourceManager.GetString("MudDataGrid.is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is after.
        /// </summary>
        public static string MudDataGrid_is_after {
            get {
                return ResourceManager.GetString("MudDataGrid.is after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is before.
        /// </summary>
        public static string MudDataGrid_is_before {
            get {
                return ResourceManager.GetString("MudDataGrid.is before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is empty.
        /// </summary>
        public static string MudDataGrid_is_empty {
            get {
                return ResourceManager.GetString("MudDataGrid.is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not.
        /// </summary>
        public static string MudDataGrid_is_not {
            get {
                return ResourceManager.GetString("MudDataGrid.is not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not empty.
        /// </summary>
        public static string MudDataGrid_is_not_empty {
            get {
                return ResourceManager.GetString("MudDataGrid.is not empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is on or after.
        /// </summary>
        public static string MudDataGrid_is_on_or_after {
            get {
                return ResourceManager.GetString("MudDataGrid.is on or after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is on or before.
        /// </summary>
        public static string MudDataGrid_is_on_or_before {
            get {
                return ResourceManager.GetString("MudDataGrid.is on or before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not contains.
        /// </summary>
        public static string MudDataGrid_not_contains {
            get {
                return ResourceManager.GetString("MudDataGrid.not contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not equals.
        /// </summary>
        public static string MudDataGrid_not_equals {
            get {
                return ResourceManager.GetString("MudDataGrid.not equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string MudDataGrid_Operator {
            get {
                return ResourceManager.GetString("MudDataGrid.Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Data.
        /// </summary>
        public static string MudDataGrid_RefreshData {
            get {
                return ResourceManager.GetString("MudDataGrid.RefreshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MudDataGrid_Save {
            get {
                return ResourceManager.GetString("MudDataGrid.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string MudDataGrid_ShowAll {
            get {
                return ResourceManager.GetString("MudDataGrid.ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts with.
        /// </summary>
        public static string MudDataGrid_starts_with {
            get {
                return ResourceManager.GetString("MudDataGrid.starts with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string MudDataGrid_True {
            get {
                return ResourceManager.GetString("MudDataGrid.True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        public static string MudDataGrid_Ungroup {
            get {
                return ResourceManager.GetString("MudDataGrid.Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsort.
        /// </summary>
        public static string MudDataGrid_Unsort {
            get {
                return ResourceManager.GetString("MudDataGrid.Unsort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string MudDataGrid_Value {
            get {
                return ResourceManager.GetString("MudDataGrid.Value", resourceCulture);
            }
        }
    }
}
