name: Feature Request
description: Request a new feature
labels: [triage, enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Use this template **only** to ask for new features.  
        If you have a question, please use [GitHub Discussions](https://github.com/MudBlazor/MudBlazor/discussions) or [Discord](https://discord.gg/mudblazor).
  - type: dropdown
    id: enhancement-type
    attributes:
      label: Feature type
      options:
        - Enhance component
        - New component
        - Performance improvement
        - Other
    validations:
      required: true
  - type: input
    id: component-name
    attributes:
      label: Component name
      description: If your request is about a component, tell us its name.
      placeholder: MudComponent
  - type: textarea
    id: related-problem
    attributes:
      label: Is this request related to a problem?
      description: Briefly describe the problem. For example, I'm frustrated when [...]
      placeholder: Describe your problem
  - type: textarea
    id: expected-behavior
    attributes:
      label: Describe the solution you'd like
      description: Describe what you would like to see happen.
      placeholder: Describe your request
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Have you seen this feature anywhere else?
      description: If possible, add links to Material Design guidelines, other implementations, screenshots, or videos.
      placeholder: Add examples
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Describe any other solutions or work‑arounds you have tried or considered.
      placeholder: Describe alternatives
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/MudBlazor/MudBlazor/blob/dev/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
