using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Components;

namespace MudBlazor.Docs.Compiler
{
    public static class DocStringsGenerator
    {
        public const string DocStringsFile = "DocStrings.generated.cs";

        public static void GenerateDocStrings(string doc_path)
        {
            var doc_strings_path = Directory.EnumerateFiles(doc_path, DocStringsFile, SearchOption.AllDirectories).FirstOrDefault();
            if (doc_strings_path == null)
                throw new InvalidOperationException("File not found: " + DocStringsFile);
            using (var f = File.Open(doc_strings_path, FileMode.Create))
            using (var w = new StreamWriter(f) { NewLine = "\n" })
            {
                w.WriteLine("// NOTE: this file is autogenerated. Any changes will be overwritten!");
                w.WriteLine(
                    @"namespace MudBlazor.Docs.Models
{
    public static partial class DocStrings
    {
");
                var assembly = typeof(MudText).Assembly;
                foreach (var type in assembly.GetTypes().OrderBy(t => GetSaveTypename(t)))
                {
                    foreach (var info in type.GetPropertyInfosWithAttribute<ParameterAttribute>())
                    {
                        var doc = info.GetDocumentation();
                        doc = Regex.Replace(doc ?? "", @"</?.+?>", "");
                        w.WriteLine($"public const string {GetSaveTypename(type).TrimEnd('_')}_{info.Name} = @\"{EscapeDescription(doc)}\";\n");
                    }
                }

                w.WriteLine(
                    @"    }
}
");
                w.Flush();
            }
        }

        public static string GetSaveTypename(Type t) => Regex.Replace(t.ConvertToCSharpSource(), @"[\.<>]", "_");

        private static string EscapeDescription(string doc)
        {
            return doc.Replace("\"", "\"\"").Trim();
        }

    }
}
