//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudBlazor.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MudBlazor.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mudblazor.com/features/analyzers.
        /// </summary>
        internal static string HelpLinkUrl {
            get {
                return ResourceManager.GetString("HelpLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a component parameter, it could be an attribute..
        /// </summary>
        internal static string MUD0002Description {
            get {
                return ResourceManager.GetString("MUD0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal Attribute &apos;{0}&apos; on &apos;{1}&apos; using pattern &apos;{2}&apos; source location &apos;{3}&apos;.
        /// </summary>
        internal static string MUD0002MessageFormat {
            get {
                return ResourceManager.GetString("MUD0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown MudBlazor attribute/parameter.
        /// </summary>
        internal static string MUD0002Title {
            get {
                return ResourceManager.GetString("MUD0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading a parameter state property is not allowed..
        /// </summary>
        internal static string MUD0010Description {
            get {
                return ResourceManager.GetString("MUD0010Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading &apos;{0}&apos; parameter state property is not allowed. Use the backing ParameterState&lt;{1}&gt;.Value instance instead..
        /// </summary>
        internal static string MUD0010MessageFormat {
            get {
                return ResourceManager.GetString("MUD0010MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading ParameterState property.
        /// </summary>
        internal static string MUD0010Title {
            get {
                return ResourceManager.GetString("MUD0010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to a parameter state property is not allowed..
        /// </summary>
        internal static string MUD0011Description {
            get {
                return ResourceManager.GetString("MUD0011Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to &apos;{0}&apos; parameter state property is not allowed. Use the backing ParameterState&lt;{1}&gt;.SetValueAsync instead..
        /// </summary>
        internal static string MUD0011MessageFormat {
            get {
                return ResourceManager.GetString("MUD0011MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to ParameterState property.
        /// </summary>
        internal static string MUD0011Title {
            get {
                return ResourceManager.GetString("MUD0011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External access of a parameter state property is not allowed..
        /// </summary>
        internal static string MUD0012Description {
            get {
                return ResourceManager.GetString("MUD0012Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External access of &apos;{0}&apos; parameter state property is not allowed. Use GetState(x =&gt; x.{0}) instead..
        /// </summary>
        internal static string MUD0012MessageFormat {
            get {
                return ResourceManager.GetString("MUD0012MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External access of ParameterState property.
        /// </summary>
        internal static string MUD0012Title {
            get {
                return ResourceManager.GetString("MUD0012Title", resourceCulture);
            }
        }
    }
}
