trigger:
- none
pr:
- none

stages:
- stage: Stage
  jobs:
  - job: Stage
    displayName: stage mudblazor.com
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UseDotNet@2
      displayName: Install .NET Core 5.0
      inputs:
        # Using 5.0.x SDK for 3.1.x builds no problem.
        # Includes 5.0.x runtime for net5.0 tests.
        version: '5.0.x'

    - task: UseDotNet@2
      displayName: Install .NET Core 3.1
      inputs:
        # Include 3.1.x runtime to run netcareapp3.1 tests.
        version: '3.1.x'
        packageType: runtime

    - task: DotNetCoreCLI@2
      displayName: "Build"
      inputs:
        command: 'build'
        arguments: './src/MudBlazor.Docs.Server/MudBlazor.Docs.Server.csproj --configuration release'

    - task: DotNetCoreCLI@2
      displayName: "Publish"
      inputs:
        command: 'publish'
        publishWebProjects: false
        arguments: './src/MudBlazor.Docs.Server/MudBlazor.Docs.Server.csproj --configuration release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: AzureWebApp@1
      displayName: 'Azure Web App Deploy'
      inputs:
        azureSubscription: Azure-MudBlazor
        appType: webApp
        appName: MudBlazor
        package: $(Build.ArtifactStagingDirectory)/**/*.zip
        slotName: staging