<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.12" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.1" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MudBlazor" />
    <InternalsVisibleTo Include="MudBlazor.Docs" />
    <InternalsVisibleTo Include="MudBlazor.UnitTests.Shared" />
    <InternalsVisibleTo Include="MudBlazor.UnitTests" />
    <InternalsVisibleTo Include="MudBlazor.UnitTests.Docs" />
    <InternalsVisibleTo Include="MudBlazor.UnitTests.Viewer" />
    <InternalsVisibleTo Include="MudBlazor.Benchmarks" />
    <!--We need to make internal types to be visible for mocking-->
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
