name: build-test-mudblazor

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # We should switch to a newer version and config files. Then we can also cache the dependency.
      - name: Install eslint
        run: npm i -g eslint@8.57.0

      - name: Check JS is ES6 compliant
        working-directory: src
        run: eslint --env 'es6' MudBlazor/TScripts

      - name: Cache NuGet packages
        uses: actions/cache@v5
        with:
          key: ${{ github.repository }}-nuget-${{ hashFiles('**/*.csproj') }}
          path: ${{ env.NUGET_PACKAGES }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          # We need all runtimes for the tests
          dotnet-version: |
            10.x
            9.x
            8.x

      - name: Restore dependencies
        working-directory: src
        run: dotnet restore

      - name: Build solution
        working-directory: src
        run: dotnet build -c Release --no-restore

      - name: Test solution
        working-directory: src
        run: dotnet test -c Release --no-build --blame-hang --blame-hang-timeout 60s /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByAttribute='ExcludeFromCodeCoverageAttribute' /p:ExcludeByAttribute='CompilerGeneratedAttribute' /p:ExcludeByFile='**/*.g.cs' /p:Include='[MudBlazor]*' /p:SkipAutoProps=true /p:CoverletOutput='./TestResults/'

      - name: Publish coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
