name: ci-dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    

jobs:
  pipeline:
    name: Pipeline
    uses: MudBlazor/MudBlazor/.github/workflows/template-pipeline.yml@dev
    with:
      dotnet-version: 6.0.x
      dotnet-prerelease: true
      publish-coverage: true
      deploy-web-app: true
      deploy-condition: 'refs/heads/dev'
      deploy-web-app-name: mudblazor-dev
    secrets:
      publish-profile: ${{ secrets.PUBLISH_MUDBLAZOR_DEV }}


