name: deploy-prod

on:
  workflow_dispatch:
    inputs:
        deploy-task:
          description: 'Publish to staging or swap slots'
          required: true
          default: 'publish' 
          type: choice
          options:
          - publish
          - slot-swap

jobs:
  pipeline:
    uses: MudBlazor/Workflows/.github/workflows/template-pipeline.yml@main
    if: ${{ github.event.inputs.deploy-task == 'publish' }}
    with:
      dotnet-version: 6.0.x
      deploy-web-app: true
      deploy-condition: 'refs/heads/master'
      deploy-web-app-name: mudblazor
      deploy-web-app-slot-name: staging
      working-directory: ./src/MudBlazor.Docs.WasmHost
    secrets:
      publish-profile: ${{ secrets.PUBLISH_MUDBLAZOR }}
      
  azure-app:
    uses: MudBlazor/Workflows/.github/workflows/azure-app-service.yml@main
    if: ${{ github.event.inputs.deploy-task == 'slot-swap' }}
    with:
      azure-app-name: mudblazor
    secrets:
      azure-cred: ${{ secrets.CHANGETHISWHENYOUWAKEUP }}
