name: deploy-mudblazor-nuget

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get-version.outputs.VERSION }}
    steps:
      - name: Get version
        id: get-version
        run: |
          VERSION="${{ github.ref_name }}"
          echo "VERSION=${VERSION#v}" >> $GITHUB_OUTPUT

  deploy-nuget:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - uses: actions/checkout@v7

      - name: Cache NuGet packages
        uses: actions/cache@v6
        with:
          key: ${{ github.repository }}-nuget-${{ hashFiles('**/*.csproj') }}
          path: ${{ env.NUGET_PACKAGES }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Restore dependencies
        working-directory: src/MudBlazor
        run: dotnet restore

      - name: Pack nuget package
        working-directory: ./src/MudBlazor
        run: dotnet pack -c Release --no-restore --output nupkgs /p:Version=${{ needs.get-version.outputs.VERSION }}

      - name: Check package contains css
        shell: pwsh
        run: ./tools/CheckPackageContainsStaticAssets.ps1 ./src/MudBlazor/nupkgs MudBlazor.min.css

      - name: Check package contains js
        shell: pwsh
        run: ./tools/CheckPackageContainsStaticAssets.ps1 ./src/MudBlazor/nupkgs MudBlazor.min.js

      - name: Publish nuget package
        working-directory: ./src/MudBlazor
        run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
