name: deploy-nuget

on:
  workflow_dispatch:
    inputs:
        nuget-version:
          description: 'Tag to publish v[0-9]+.[0-9]+.[0-9]+*'
          required: true
          default: '' 
          type: string
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+*"
env:
  VERSION: 1.0.0
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set tag from input
      if: ${{ github.event.inputs.nuget-version != '' }}
      env:
        TAG: ${{ github.event.inputs.nuget-version }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
    - name: Set version variable from tag
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: 'refs/tags/v${{ env.VERSION }}'
    - name: Setup dotnet version
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - name: Pack nuget package
      run: dotnet pack -c Release --output nupkgs /p:PackageVersion=$VERSION
      working-directory: ./src/MudBlazor
    #- name: Upload Artifact (for testing before publish)
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: nuget
    #    path: ./src/MudBlazor/nupkgs/*.nupkg
    #    retention-days: 1
    - name: Publish nuget package
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
      working-directory: ./src/MudBlazor