name: mudbot

on:
  pull_request:
    

jobs:
  pr-check:
    name: PR Check
    runs-on: ubuntu-latest
    steps:
    - uses: MudBlazor/MudBot@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

