name: mudbot

on:
  pull_request:
    types:
      - opened
    
jobs:
  pr-check:
    name: PR Check
    runs-on: ubuntu-latest
    steps:
    - uses: MudBlazor/MudBot@v1.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

