name: prepare-release

on:
  workflow_dispatch:
    inputs:
      mud-version:
        description: 'The new MudBlazor version number'     
        required: true
        default: '6.0.?'
  
jobs:
  pipeline:
    name: Pipeline
    uses: MudBlazor/MudBlazor/.github/workflows/template-pipeline.yml@master
    with:
      dotnet-version: 6.0.x
      publish-coverage: true
      deploy-web-app: true
      deploy-condition: 'refs/heads/master'
      deploy-web-app-name: mudblazor
      deploy-web-app-slot-name: 'staging'
    secrets:
      publish-profile: ${{ secrets.PUBLISH_MUDBLAZOR }}
      
#  pack-library:
#    name: Pack / Publish Library
#    needs: pipeline
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./src
#    
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Setup dotnet version
#        uses: actions/setup-dotnet@v1
#        with: 
#          dotnet-version: 6.0.x
#          
#      - name: Pack
#        run: dotnet pack ./MudBlazor -c Release -o ${{env.DOTNET_ROOT}}/packages        
#      - name: Publish
#        run: dotnet nuget push ${{env.DOTNET_ROOT}}/packages/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
      
  update-trymudblazor:
    name: Update TryMudBlazor
    needs: pipeline
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
          repository: mudblazor/trymudblazor
          event-type: mudblazor-release
          client-payload: '{"mud-version": "${{ github.event.inputs.mud-version }}", "dotnet-version": "6.0.x"}'

